lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", DiscussWeb do
    pipe_through :browser
    

    resources "/", TopicController
    # get "/", TopicController, :index
    # get "/topics", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id", TopicController, :show
    # put "/topics/:id", TopicController, :update
    # get "/topics/:id/edit", TopicController, :edit
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

lib/discuss/application.ex
defmodule Discuss.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Discuss.Repo,
      # Start the endpoint when the application starts
      DiscussWeb.Endpoint
      # Starts a worker by calling: Discuss.Worker.start_link(arg)
      # {Discuss.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo,
    otp_app: :discuss,
    adapter: Ecto.Adapters.Postgres
end

lib/discuss_web/controllers/auth_controller.ex
defmodule DiscussWeb.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth
  alias Discuss.User
  alias Uberauth.Strategy.Helpers
  alias Discuss.Repo

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: auth.provider}
    changeset = User.changeset(%User{}, user_params)
    signin(conn, changeset) 
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: Routes.topic_path(conn, :index))
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Error signing in")
        |> redirect(to: Routes.topic_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
     case Repo.get_by(User, email: changeset.changes.email) do
      nil -> Repo.insert(changeset)
      user -> {:ok, user}
     end
  end

end

lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  alias Discuss.Repo
  alias Discuss.Topic

  plug DiscussWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:update, :edit, :delete]

  def index(conn, _params) do
    IO.inspect(conn.assigns)
    topics = Repo.all(Topic)
    render conn, "index.html", topics: topics
  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})
    
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do
    # changeset = Topic.changeset(%Topic{}, topic)
    changeset = conn.assigns.user
      |> Ecto.build_assoc(:topics)
      |> Topic.changeset(topic)
    

     case Repo.insert(changeset) do
      {:ok, _topic} -> 
        conn
        |> put_flash(:info, "Topic Created")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} -> 
        render conn, "new.html", changeset: changeset
     end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render conn, "edit.html", changeset: changeset, topic: topic
  end
  
  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(old_topic, topic) 
    
    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Updated")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, topic: old_topic
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    Repo.get!(Topic, topic_id) |> Repo.delete!
    
    conn
    |> put_flash(:info, "Topic Deleted")
    |> redirect(to: Routes.topic_path(conn, :index))
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id}} = conn

    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot edit that")
      |> redirect(to: Routes.topic_path(conn, :index))
      |> halt()
    end
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Discuss · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: Routes.auth_path(@conn, :request, "signout") %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: Routes.auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript", src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

lib/discuss_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br/>does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
      <li>
        <a href="https://google.com.au/">Google</a>
      </li>
    </ul>
  </div>
  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :update, @topic), fn f ->  %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/index.html.eex
<h5>Hello</h5>
<ul class="collection">
<%= for topic <- @topics do %>
  <li class="collection-item">
    <%= link topic.title, to: Routes.topic_path(@conn, :show, topic) %>
    <%= if @conn.assigns.user do %>
      <%= if @conn.assigns.user.id == topic.user_id do %>
      <div class="right">
        <%= link "Edit", to: Routes.topic_path(@conn, :edit, topic) %>
        <%= link "Delete", to: Routes.topic_path(@conn, :delete, topic), method: :delete %>
      </div>
      <%= end %>
    <%= end %>
  </li>
<% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: Routes.topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <%= end %>
</div>

lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/show.html.eex
<%= @topic.title %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    window.createSocket(<%= @topic.id %>);
  })
</script>